### ISSUE TITLE
File Sideload requirement

### ISSUE THREAD

**Issue by akprtll** [omeka-s-modules/Osii#7]
Experimenting with importing items from one site to another, it seems to be the case that if your source site used the File Sideload module to upload images, the destination site also needs to have the File Sideload module installed in order for the import to work correctly (even though the imported images do not end up in the destination site's Sideload folder).

**Comment by jimsafley** [comment]
Yes, modules that add a media ingester (like FileSideload) must implement a media ingester mapper to tell the OSII import process how to ingest the media. FileSideload has [implemented a mapper](https://github.com/omeka-s-modules/FileSideload/blob/master/src/Osii/MediaIngesterMapper/Sideload.php) since v1.6.0. It tells the local installation to use the "url" ingester using the `o:original_url`, which is located in the remote installation's /files/original directory, not its sideload directory.
